create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	price VARCHAR(50) NOT NULL
);
insert into car (id, make, model, price) values (1, 'Volkswagen', 'Golf', '¥6.41');
insert into car (id, make, model, price) values (2, 'Volkswagen', 'Passat', '¥4.46');
insert into car (id, make, model, price) values (3, 'Cadillac', 'XLR', '¥5.26');
insert into car (id, make, model, price) values (4, 'Toyota', 'Corolla', '¥0.78');
insert into car (id, make, model, price) values (5, 'Lincoln', 'MKX', '¥5.12');
insert into car (id, make, model, price) values (6, 'Dodge', 'Neon', '¥7.70');
insert into car (id, make, model, price) values (7, 'Ford', 'Festiva', '¥3.54');
insert into car (id, make, model, price) values (8, 'Mitsubishi', 'Eclipse', '¥0.57');
insert into car (id, make, model, price) values (9, 'Mazda', 'Familia', '¥7.11');
insert into car (id, make, model, price) values (10, 'Ford', 'Explorer', '¥7.65');
insert into car (id, make, model, price) values (11, 'Mitsubishi', 'Montero', '¥5.38');
insert into car (id, make, model, price) values (12, 'Infiniti', 'I', '¥1.19');
insert into car (id, make, model, price) values (13, 'Audi', 'Cabriolet', '¥2.94');
insert into car (id, make, model, price) values (14, 'Mitsubishi', 'Outlander', '¥4.35');
insert into car (id, make, model, price) values (15, 'Mitsubishi', 'GTO', '¥2.00');
insert into car (id, make, model, price) values (16, 'Mitsubishi', 'Precis', '¥9.57');
insert into car (id, make, model, price) values (17, 'Mazda', 'Millenia', '¥4.86');
insert into car (id, make, model, price) values (18, 'Buick', 'Lucerne', '¥5.50');
insert into car (id, make, model, price) values (19, 'Honda', 'Element', '¥0.87');
insert into car (id, make, model, price) values (20, 'Nissan', 'Pathfinder', '¥3.93');
insert into car (id, make, model, price) values (21, 'Infiniti', 'M', '¥1.32');
insert into car (id, make, model, price) values (22, 'Lamborghini', 'Diablo', '¥2.09');
insert into car (id, make, model, price) values (23, 'Hyundai', 'Excel', '¥3.45');
insert into car (id, make, model, price) values (24, 'Audi', '100', '¥0.54');
insert into car (id, make, model, price) values (25, 'Mazda', 'B-Series', '¥2.40');
insert into car (id, make, model, price) values (26, 'Mazda', 'MPV', '¥5.24');
insert into car (id, make, model, price) values (27, 'Mazda', '323', '¥3.50');
insert into car (id, make, model, price) values (28, 'Suzuki', 'Daewoo Magnus', '¥9.32');
insert into car (id, make, model, price) values (29, 'Mitsubishi', 'Eclipse', '¥8.38');
insert into car (id, make, model, price) values (30, 'Dodge', 'Ram Van 2500', '¥8.51');
insert into car (id, make, model, price) values (31, 'Volvo', '850', '¥6.32');
insert into car (id, make, model, price) values (32, 'Cadillac', 'Escalade ESV', '¥3.93');
insert into car (id, make, model, price) values (33, 'Ford', 'Torino', '¥3.19');
insert into car (id, make, model, price) values (34, 'Volvo', 'S40', '¥6.88');
insert into car (id, make, model, price) values (35, 'Pontiac', 'Turbo Firefly', '¥9.14');
insert into car (id, make, model, price) values (36, 'Ford', 'Edge', '¥3.46');
insert into car (id, make, model, price) values (37, 'Pontiac', 'Tempest', '¥8.26');
insert into car (id, make, model, price) values (38, 'Isuzu', 'i-Series', '¥7.66');
insert into car (id, make, model, price) values (39, 'Subaru', 'Outback', '¥6.52');
insert into car (id, make, model, price) values (40, 'Jaguar', 'XK Series', '¥9.91');
insert into car (id, make, model, price) values (41, 'Volkswagen', 'GTI', '¥1.55');
insert into car (id, make, model, price) values (42, 'Maserati', 'Quattroporte', '¥2.58');
insert into car (id, make, model, price) values (43, 'Nissan', 'Frontier', '¥1.31');
insert into car (id, make, model, price) values (44, 'Volkswagen', 'GTI', '¥1.34');
insert into car (id, make, model, price) values (45, 'Chevrolet', 'Colorado', '¥0.31');
insert into car (id, make, model, price) values (46, 'Porsche', '911', '¥9.93');
insert into car (id, make, model, price) values (47, 'Volkswagen', 'Tiguan', '¥10.00');
insert into car (id, make, model, price) values (48, 'Chrysler', 'Concorde', '¥9.99');
insert into car (id, make, model, price) values (49, 'GMC', 'Yukon Denali', '¥8.36');
insert into car (id, make, model, price) values (50, 'Isuzu', 'Trooper', '¥7.68');
insert into car (id, make, model, price) values (51, 'Cadillac', 'CTS', '¥8.16');
insert into car (id, make, model, price) values (52, 'Saab', '9-3', '¥7.02');
insert into car (id, make, model, price) values (53, 'Cadillac', 'Eldorado', '¥6.96');
insert into car (id, make, model, price) values (54, 'Nissan', 'Maxima', '¥8.21');
insert into car (id, make, model, price) values (55, 'Pontiac', 'Fiero', '¥4.29');
insert into car (id, make, model, price) values (56, 'Mitsubishi', 'Outlander', '¥4.68');
insert into car (id, make, model, price) values (57, 'Lexus', 'LX', '¥5.53');
insert into car (id, make, model, price) values (58, 'Nissan', 'Xterra', '¥2.51');
insert into car (id, make, model, price) values (59, 'Toyota', 'Solara', '¥2.29');
insert into car (id, make, model, price) values (60, 'Chevrolet', 'Express 3500', '¥4.35');
insert into car (id, make, model, price) values (61, 'Chrysler', '300', '¥5.11');
insert into car (id, make, model, price) values (62, 'Ford', 'Escort', '¥1.81');
insert into car (id, make, model, price) values (63, 'Audi', 'Quattro', '¥0.59');
insert into car (id, make, model, price) values (64, 'Mercedes-Benz', 'E-Class', '¥5.84');
insert into car (id, make, model, price) values (65, 'Chrysler', 'Voyager', '¥0.82');
insert into car (id, make, model, price) values (66, 'Volkswagen', 'Type 2', '¥6.19');
insert into car (id, make, model, price) values (67, 'Hyundai', 'Sonata', '¥7.75');
insert into car (id, make, model, price) values (68, 'Ford', 'Crown Victoria', '¥6.79');
insert into car (id, make, model, price) values (69, 'Porsche', 'Boxster', '¥7.62');
insert into car (id, make, model, price) values (70, 'Jaguar', 'XK', '¥4.97');
insert into car (id, make, model, price) values (71, 'Ford', 'F150', '¥3.63');
insert into car (id, make, model, price) values (72, 'Pontiac', 'Daewoo Kalos', '¥5.19');
insert into car (id, make, model, price) values (73, 'Mitsubishi', 'Precis', '¥4.22');
insert into car (id, make, model, price) values (74, 'GMC', '1500', '¥5.95');
insert into car (id, make, model, price) values (75, 'Cadillac', 'CTS', '¥1.80');
insert into car (id, make, model, price) values (76, 'GMC', 'Yukon', '¥4.68');
insert into car (id, make, model, price) values (77, 'Suzuki', 'Vitara', '¥9.30');
insert into car (id, make, model, price) values (78, 'Scion', 'tC', '¥5.82');
insert into car (id, make, model, price) values (79, 'Chevrolet', 'Venture', '¥6.95');
insert into car (id, make, model, price) values (80, 'Pontiac', 'Grand Am', '¥7.24');
insert into car (id, make, model, price) values (81, 'Lotus', 'Esprit', '¥4.53');
insert into car (id, make, model, price) values (82, 'GMC', 'Savana 1500', '¥8.07');
insert into car (id, make, model, price) values (83, 'Toyota', 'Land Cruiser', '¥4.64');
insert into car (id, make, model, price) values (84, 'Chevrolet', 'Cavalier', '¥9.57');
insert into car (id, make, model, price) values (85, 'Volkswagen', 'R32', '¥1.08');
insert into car (id, make, model, price) values (86, 'Mercury', 'Grand Marquis', '¥9.36');
insert into car (id, make, model, price) values (87, 'Ford', 'F250', '¥3.31');
insert into car (id, make, model, price) values (88, 'Mazda', 'Protege', '¥2.70');
insert into car (id, make, model, price) values (89, 'BMW', '3 Series', '¥1.97');
insert into car (id, make, model, price) values (90, 'Volvo', 'V70', '¥0.68');
insert into car (id, make, model, price) values (91, 'Cadillac', 'Catera', '¥3.61');
insert into car (id, make, model, price) values (92, 'Mazda', 'MPV', '¥5.89');
insert into car (id, make, model, price) values (93, 'Ford', 'Bronco', '¥1.06');
insert into car (id, make, model, price) values (94, 'Dodge', 'Ram Van 2500', '¥0.08');
insert into car (id, make, model, price) values (95, 'Dodge', 'Intrepid', '¥0.08');
insert into car (id, make, model, price) values (96, 'Buick', 'Riviera', '¥5.39');
insert into car (id, make, model, price) values (97, 'Volkswagen', 'GTI', '¥4.70');
insert into car (id, make, model, price) values (98, 'Volvo', 'S80', '¥6.28');
insert into car (id, make, model, price) values (99, 'Chevrolet', 'Express 2500', '¥7.14');
insert into car (id, make, model, price) values (100, 'Chrysler', 'Concorde', '¥5.32');
insert into car (id, make, model, price) values (101, 'Mitsubishi', 'Lancer Evolution', '¥1.12');
insert into car (id, make, model, price) values (102, 'Audi', 'A4', '¥4.40');
insert into car (id, make, model, price) values (103, 'Saab', '9-7X', '¥2.86');
insert into car (id, make, model, price) values (104, 'GMC', 'Savana', '¥5.83');
insert into car (id, make, model, price) values (105, 'BMW', '5 Series', '¥3.05');
insert into car (id, make, model, price) values (106, 'Hummer', 'H1', '¥0.50');
insert into car (id, make, model, price) values (107, 'Chevrolet', 'Sportvan G20', '¥1.33');
insert into car (id, make, model, price) values (108, 'Lexus', 'LS', '¥6.00');
insert into car (id, make, model, price) values (109, 'GMC', 'Terrain', '¥8.43');
insert into car (id, make, model, price) values (110, 'Volkswagen', 'Tiguan', '¥1.38');
insert into car (id, make, model, price) values (111, 'Saturn', 'Outlook', '¥7.37');
insert into car (id, make, model, price) values (112, 'Jeep', 'Grand Cherokee', '¥6.63');
insert into car (id, make, model, price) values (113, 'Ford', 'F350', '¥4.28');
insert into car (id, make, model, price) values (114, 'Buick', 'Enclave', '¥2.25');
insert into car (id, make, model, price) values (115, 'Suzuki', 'Verona', '¥6.24');
insert into car (id, make, model, price) values (116, 'Chevrolet', 'Suburban 1500', '¥9.62');
insert into car (id, make, model, price) values (117, 'BMW', 'X5', '¥3.13');
insert into car (id, make, model, price) values (118, 'Buick', 'LeSabre', '¥2.87');
insert into car (id, make, model, price) values (119, 'Chevrolet', 'Cavalier', '¥3.55');
insert into car (id, make, model, price) values (120, 'Chevrolet', 'Beretta', '¥9.23');
insert into car (id, make, model, price) values (121, 'Chevrolet', 'Camaro', '¥3.09');
insert into car (id, make, model, price) values (122, 'Ford', 'Fusion', '¥1.25');
insert into car (id, make, model, price) values (123, 'Chevrolet', 'Blazer', '¥9.53');
insert into car (id, make, model, price) values (124, 'Lincoln', 'Aviator', '¥4.17');
insert into car (id, make, model, price) values (125, 'Saturn', 'VUE', '¥2.04');
insert into car (id, make, model, price) values (126, 'Chrysler', 'Sebring', '¥8.77');
insert into car (id, make, model, price) values (127, 'Mitsubishi', '3000GT', '¥0.54');
insert into car (id, make, model, price) values (128, 'Infiniti', 'G', '¥6.66');
insert into car (id, make, model, price) values (129, 'Buick', 'Skylark', '¥6.66');
insert into car (id, make, model, price) values (130, 'Chevrolet', 'Suburban 1500', '¥0.25');
insert into car (id, make, model, price) values (131, 'Audi', '5000CS Quattro', '¥9.96');
insert into car (id, make, model, price) values (132, 'Cadillac', 'Escalade', '¥1.77');
insert into car (id, make, model, price) values (133, 'BMW', 'Z3', '¥0.61');
insert into car (id, make, model, price) values (134, 'Honda', 'Accord', '¥7.05');
insert into car (id, make, model, price) values (135, 'BMW', 'M3', '¥2.57');
insert into car (id, make, model, price) values (136, 'Volkswagen', 'Beetle', '¥2.17');
insert into car (id, make, model, price) values (137, 'Chevrolet', 'Avalanche 1500', '¥5.19');
insert into car (id, make, model, price) values (138, 'Ford', 'Explorer Sport Trac', '¥5.08');
insert into car (id, make, model, price) values (139, 'Mitsubishi', 'Pajero', '¥7.94');
insert into car (id, make, model, price) values (140, 'Toyota', 'RAV4', '¥7.42');
insert into car (id, make, model, price) values (141, 'Volkswagen', 'GTI', '¥6.54');
insert into car (id, make, model, price) values (142, 'Dodge', 'Ram 1500', '¥8.13');
insert into car (id, make, model, price) values (143, 'Honda', 'Civic', '¥0.34');
insert into car (id, make, model, price) values (144, 'GMC', 'Rally Wagon G3500', '¥0.80');
insert into car (id, make, model, price) values (145, 'Mitsubishi', 'Pajero', '¥6.96');
insert into car (id, make, model, price) values (146, 'Chevrolet', 'Astro', '¥0.30');
insert into car (id, make, model, price) values (147, 'Dodge', 'Neon', '¥7.79');
insert into car (id, make, model, price) values (148, 'Lotus', 'Esprit', '¥1.12');
insert into car (id, make, model, price) values (149, 'Suzuki', 'Forenza', '¥4.33');
insert into car (id, make, model, price) values (150, 'Ford', 'Courier', '¥0.59');
insert into car (id, make, model, price) values (151, 'Saab', '900', '¥8.30');
insert into car (id, make, model, price) values (152, 'Chevrolet', 'Suburban 1500', '¥5.62');
insert into car (id, make, model, price) values (153, 'Honda', 'Accord', '¥3.52');
insert into car (id, make, model, price) values (154, 'Dodge', 'Shadow', '¥7.58');
insert into car (id, make, model, price) values (155, 'Volvo', 'S80', '¥2.76');
insert into car (id, make, model, price) values (156, 'Oldsmobile', 'Intrigue', '¥0.11');
insert into car (id, make, model, price) values (157, 'Lamborghini', 'Diablo', '¥2.04');
insert into car (id, make, model, price) values (158, 'Pontiac', 'Grand Am', '¥4.14');
insert into car (id, make, model, price) values (159, 'Mercedes-Benz', 'W201', '¥1.35');
insert into car (id, make, model, price) values (160, 'Chevrolet', 'S10', '¥7.53');
insert into car (id, make, model, price) values (161, 'Subaru', 'Alcyone SVX', '¥1.82');
insert into car (id, make, model, price) values (162, 'Ford', 'Club Wagon', '¥4.67');
insert into car (id, make, model, price) values (163, 'Porsche', '944', '¥5.29');
insert into car (id, make, model, price) values (164, 'Acura', 'TSX', '¥0.97');
insert into car (id, make, model, price) values (165, 'Pontiac', 'Grand Prix', '¥2.72');
insert into car (id, make, model, price) values (166, 'Toyota', 'FJ Cruiser', '¥0.06');
insert into car (id, make, model, price) values (167, 'GMC', 'Suburban 1500', '¥2.37');
insert into car (id, make, model, price) values (168, 'Plymouth', 'Voyager', '¥5.48');
insert into car (id, make, model, price) values (169, 'Dodge', 'Sprinter', '¥1.10');
insert into car (id, make, model, price) values (170, 'Plymouth', 'Colt Vista', '¥3.13');
insert into car (id, make, model, price) values (171, 'Mercedes-Benz', '600SEC', '¥5.72');
insert into car (id, make, model, price) values (172, 'Mercedes-Benz', '300SE', '¥6.60');
insert into car (id, make, model, price) values (173, 'Land Rover', 'Defender', '¥9.52');
insert into car (id, make, model, price) values (174, 'Chevrolet', 'Silverado 1500', '¥0.87');
insert into car (id, make, model, price) values (175, 'Mitsubishi', 'Eclipse', '¥2.60');
insert into car (id, make, model, price) values (176, 'Mazda', 'Miata MX-5', '¥5.49');
insert into car (id, make, model, price) values (177, 'Hyundai', 'Veracruz', '¥9.59');
insert into car (id, make, model, price) values (178, 'Pontiac', 'Grand Am', '¥8.42');
insert into car (id, make, model, price) values (179, 'Chevrolet', 'Camaro', '¥4.80');
insert into car (id, make, model, price) values (180, 'Ford', 'Econoline E250', '¥1.27');
insert into car (id, make, model, price) values (181, 'Pontiac', 'LeMans', '¥5.04');
insert into car (id, make, model, price) values (182, 'Maserati', 'Biturbo', '¥1.06');
insert into car (id, make, model, price) values (183, 'BMW', 'Z4', '¥3.00');
insert into car (id, make, model, price) values (184, 'Lexus', 'ES', '¥1.07');
insert into car (id, make, model, price) values (185, 'BMW', '3 Series', '¥0.29');
insert into car (id, make, model, price) values (186, 'Audi', 'A6', '¥1.04');
insert into car (id, make, model, price) values (187, 'Lincoln', 'MKZ', '¥9.43');
insert into car (id, make, model, price) values (188, 'Cadillac', 'DeVille', '¥1.61');
insert into car (id, make, model, price) values (189, 'BMW', '5 Series', '¥1.82');
insert into car (id, make, model, price) values (190, 'Dodge', 'Dakota', '¥9.68');
insert into car (id, make, model, price) values (191, 'Chevrolet', 'Astro', '¥3.03');
insert into car (id, make, model, price) values (192, 'Ford', 'F350', '¥2.60');
insert into car (id, make, model, price) values (193, 'Cadillac', 'Escalade', '¥2.36');
insert into car (id, make, model, price) values (194, 'Volvo', 'S80', '¥6.48');
insert into car (id, make, model, price) values (195, 'Suzuki', 'Vitara', '¥2.44');
insert into car (id, make, model, price) values (196, 'Buick', 'Rainier', '¥5.50');
insert into car (id, make, model, price) values (197, 'Maybach', '57', '¥9.63');
insert into car (id, make, model, price) values (198, 'Mercury', 'Grand Marquis', '¥7.13');
insert into car (id, make, model, price) values (199, 'Dodge', 'Ram 3500', '¥7.17');
insert into car (id, make, model, price) values (200, 'Hyundai', 'Elantra', '¥6.48');
insert into car (id, make, model, price) values (201, 'Chevrolet', 'Corsica', '¥1.42');
insert into car (id, make, model, price) values (202, 'Mazda', 'RX-7', '¥7.38');
insert into car (id, make, model, price) values (203, 'Saturn', 'Outlook', '¥5.50');
insert into car (id, make, model, price) values (204, 'Lincoln', 'Town Car', '¥7.34');
insert into car (id, make, model, price) values (205, 'Nissan', 'Frontier', '¥7.41');
insert into car (id, make, model, price) values (206, 'Mitsubishi', 'Montero', '¥9.60');
insert into car (id, make, model, price) values (207, 'Toyota', 'Corolla', '¥6.27');
insert into car (id, make, model, price) values (208, 'Lexus', 'IS', '¥3.78');
insert into car (id, make, model, price) values (209, 'Porsche', '911', '¥3.82');
insert into car (id, make, model, price) values (210, 'Mercedes-Benz', 'E-Class', '¥1.39');
insert into car (id, make, model, price) values (211, 'Chrysler', 'Cirrus', '¥3.36');
insert into car (id, make, model, price) values (212, 'Lexus', 'LX', '¥5.48');
insert into car (id, make, model, price) values (213, 'Isuzu', 'Rodeo', '¥5.36');
insert into car (id, make, model, price) values (214, 'Toyota', 'Prius', '¥8.97');
insert into car (id, make, model, price) values (215, 'Volkswagen', 'GTI', '¥0.59');
insert into car (id, make, model, price) values (216, 'Honda', 'CR-Z', '¥2.17');
insert into car (id, make, model, price) values (217, 'Chevrolet', '3500', '¥3.68');
insert into car (id, make, model, price) values (218, 'Saab', '9-4X', '¥8.38');
insert into car (id, make, model, price) values (219, 'Maybach', 'Landaulet', '¥8.59');
insert into car (id, make, model, price) values (220, 'Chevrolet', 'Monte Carlo', '¥0.41');
insert into car (id, make, model, price) values (221, 'Chevrolet', 'Corvette', '¥2.41');
insert into car (id, make, model, price) values (222, 'Chevrolet', 'Camaro', '¥8.74');
insert into car (id, make, model, price) values (223, 'Mercedes-Benz', 'Sprinter 2500', '¥9.75');
insert into car (id, make, model, price) values (224, 'Ford', 'F350', '¥4.43');
insert into car (id, make, model, price) values (225, 'Volkswagen', 'Corrado', '¥2.58');
insert into car (id, make, model, price) values (226, 'Volkswagen', 'Beetle', '¥4.15');
insert into car (id, make, model, price) values (227, 'Chrysler', '300', '¥7.31');
insert into car (id, make, model, price) values (228, 'GMC', 'Savana 2500', '¥3.37');
insert into car (id, make, model, price) values (229, 'Acura', 'RSX', '¥6.10');
insert into car (id, make, model, price) values (230, 'Volkswagen', 'Cabriolet', '¥2.65');
insert into car (id, make, model, price) values (231, 'Chevrolet', 'Lumina', '¥6.58');
insert into car (id, make, model, price) values (232, 'Mazda', '626', '¥6.86');
insert into car (id, make, model, price) values (233, 'Chevrolet', 'Suburban 2500', '¥9.03');
insert into car (id, make, model, price) values (234, 'Aston Martin', 'V12 Vantage', '¥9.06');
insert into car (id, make, model, price) values (235, 'Volvo', '960', '¥2.24');
insert into car (id, make, model, price) values (236, 'Ford', 'Bronco II', '¥5.55');
insert into car (id, make, model, price) values (237, 'Mitsubishi', 'Eclipse', '¥4.06');
insert into car (id, make, model, price) values (238, 'Nissan', 'Cube', '¥4.28');
insert into car (id, make, model, price) values (239, 'Maserati', '430', '¥8.21');
insert into car (id, make, model, price) values (240, 'Volkswagen', 'Jetta', '¥5.88');
insert into car (id, make, model, price) values (241, 'Subaru', 'Leone', '¥6.38');
insert into car (id, make, model, price) values (242, 'Subaru', 'Leone', '¥3.36');
insert into car (id, make, model, price) values (243, 'Dodge', 'Ram Van 2500', '¥2.52');
insert into car (id, make, model, price) values (244, 'Chevrolet', 'Colorado', '¥2.69');
insert into car (id, make, model, price) values (245, 'Mercedes-Benz', '300SL', '¥8.05');
insert into car (id, make, model, price) values (246, 'Dodge', 'Ram', '¥5.19');
insert into car (id, make, model, price) values (247, 'Porsche', '911', '¥1.52');
insert into car (id, make, model, price) values (248, 'Mazda', 'CX-7', '¥1.30');
insert into car (id, make, model, price) values (249, 'Toyota', 'Sequoia', '¥3.12');
insert into car (id, make, model, price) values (250, 'Toyota', '4Runner', '¥4.41');
insert into car (id, make, model, price) values (251, 'Saab', '9-3', '¥8.84');
insert into car (id, make, model, price) values (252, 'Ford', 'Escape', '¥9.35');
insert into car (id, make, model, price) values (253, 'Dodge', 'Ram Van B250', '¥3.09');
insert into car (id, make, model, price) values (254, 'Mazda', 'Miata MX-5', '¥3.73');
insert into car (id, make, model, price) values (255, 'Lexus', 'LX', '¥5.97');
insert into car (id, make, model, price) values (256, 'Ford', 'Explorer', '¥8.62');
insert into car (id, make, model, price) values (257, 'Mitsubishi', 'Lancer', '¥7.53');
insert into car (id, make, model, price) values (258, 'Plymouth', 'Acclaim', '¥7.84');
insert into car (id, make, model, price) values (259, 'Geo', 'Storm', '¥4.18');
insert into car (id, make, model, price) values (260, 'Mercury', 'Milan', '¥8.09');
insert into car (id, make, model, price) values (261, 'Nissan', 'Altima', '¥3.50');
insert into car (id, make, model, price) values (262, 'Aston Martin', 'V12 Vantage', '¥2.14');
insert into car (id, make, model, price) values (263, 'Cadillac', 'Catera', '¥9.36');
insert into car (id, make, model, price) values (264, 'Nissan', '370Z', '¥6.13');
insert into car (id, make, model, price) values (265, 'GMC', '3500', '¥2.10');
insert into car (id, make, model, price) values (266, 'Lexus', 'SC', '¥6.35');
insert into car (id, make, model, price) values (267, 'GMC', 'Yukon XL 2500', '¥6.16');
insert into car (id, make, model, price) values (268, 'Kia', 'Sedona', '¥4.00');
insert into car (id, make, model, price) values (269, 'Saab', '9-2X', '¥1.79');
insert into car (id, make, model, price) values (270, 'Lexus', 'ES', '¥4.15');
insert into car (id, make, model, price) values (271, 'Volkswagen', 'Scirocco', '¥8.79');
insert into car (id, make, model, price) values (272, 'GMC', 'Sierra', '¥9.18');
insert into car (id, make, model, price) values (273, 'Volkswagen', 'Routan', '¥2.81');
insert into car (id, make, model, price) values (274, 'Volkswagen', 'GTI', '¥3.43');
insert into car (id, make, model, price) values (275, 'Porsche', '924', '¥4.59');
insert into car (id, make, model, price) values (276, 'Mitsubishi', 'Eclipse', '¥5.32');
insert into car (id, make, model, price) values (277, 'Honda', 'Fit', '¥0.47');
insert into car (id, make, model, price) values (278, 'Pontiac', 'Firebird', '¥2.92');
insert into car (id, make, model, price) values (279, 'Acura', 'Vigor', '¥7.00');
insert into car (id, make, model, price) values (280, 'Dodge', 'Ram 1500', '¥8.95');
insert into car (id, make, model, price) values (281, 'Toyota', 'Camry Solara', '¥5.08');
insert into car (id, make, model, price) values (282, 'Toyota', 'MR2', '¥4.74');
insert into car (id, make, model, price) values (283, 'Chevrolet', 'Monte Carlo', '¥5.55');
insert into car (id, make, model, price) values (284, 'Ford', 'F250', '¥1.54');
insert into car (id, make, model, price) values (285, 'Suzuki', 'Esteem', '¥8.91');
insert into car (id, make, model, price) values (286, 'Dodge', 'Viper', '¥2.76');
insert into car (id, make, model, price) values (287, 'Ford', 'Five Hundred', '¥7.19');
insert into car (id, make, model, price) values (288, 'Volkswagen', 'R32', '¥5.80');
insert into car (id, make, model, price) values (289, 'Pontiac', 'Torrent', '¥6.37');
insert into car (id, make, model, price) values (290, 'Nissan', '300ZX', '¥6.09');
insert into car (id, make, model, price) values (291, 'Citroën', 'CX', '¥8.72');
insert into car (id, make, model, price) values (292, 'Acura', 'RL', '¥5.00');
insert into car (id, make, model, price) values (293, 'Subaru', 'Legacy', '¥1.85');
insert into car (id, make, model, price) values (294, 'Audi', 'A6', '¥0.26');
insert into car (id, make, model, price) values (295, 'GMC', 'Envoy XL', '¥5.08');
insert into car (id, make, model, price) values (296, 'Hyundai', 'XG350', '¥2.25');
insert into car (id, make, model, price) values (297, 'Lincoln', 'Continental', '¥2.23');
insert into car (id, make, model, price) values (298, 'Saturn', 'L-Series', '¥0.80');
insert into car (id, make, model, price) values (299, 'Suzuki', 'Swift', '¥2.21');
insert into car (id, make, model, price) values (300, 'Chevrolet', 'Equinox', '¥5.45');
insert into car (id, make, model, price) values (301, 'Kia', 'Sedona', '¥4.41');
insert into car (id, make, model, price) values (302, 'Isuzu', 'Space', '¥7.58');
insert into car (id, make, model, price) values (303, 'Honda', 'Passport', '¥6.60');
insert into car (id, make, model, price) values (304, 'Ford', 'Explorer Sport Trac', '¥4.44');
insert into car (id, make, model, price) values (305, 'Infiniti', 'Q', '¥5.49');
insert into car (id, make, model, price) values (306, 'Ford', 'E250', '¥1.10');
insert into car (id, make, model, price) values (307, 'Lincoln', 'Mark VII', '¥4.07');
insert into car (id, make, model, price) values (308, 'GMC', 'Yukon XL 1500', '¥3.02');
insert into car (id, make, model, price) values (309, 'Buick', 'Roadmaster', '¥2.28');
insert into car (id, make, model, price) values (310, 'Chevrolet', 'TrailBlazer', '¥8.12');
insert into car (id, make, model, price) values (311, 'Volvo', 'XC90', '¥9.92');
insert into car (id, make, model, price) values (312, 'Volvo', 'C70', '¥7.34');
insert into car (id, make, model, price) values (313, 'Hyundai', 'Scoupe', '¥6.14');
insert into car (id, make, model, price) values (314, 'GMC', 'Sonoma', '¥9.42');
insert into car (id, make, model, price) values (315, 'Alfa Romeo', '164', '¥6.92');
insert into car (id, make, model, price) values (316, 'Ford', 'Aerostar', '¥4.86');
insert into car (id, make, model, price) values (317, 'Acura', 'TL', '¥1.09');
insert into car (id, make, model, price) values (318, 'Acura', 'RSX', '¥1.21');
insert into car (id, make, model, price) values (319, 'Ford', 'E250', '¥2.01');
insert into car (id, make, model, price) values (320, 'GMC', 'Sonoma Club Coupe', '¥9.49');
insert into car (id, make, model, price) values (321, 'Ford', 'F150', '¥9.33');
insert into car (id, make, model, price) values (322, 'Volkswagen', 'Cabriolet', '¥6.35');
insert into car (id, make, model, price) values (323, 'Hyundai', 'Sonata', '¥5.09');
insert into car (id, make, model, price) values (324, 'Jeep', 'Liberty', '¥7.83');
insert into car (id, make, model, price) values (325, 'Honda', 'Prelude', '¥2.01');
insert into car (id, make, model, price) values (326, 'Honda', 'Ridgeline', '¥8.15');
insert into car (id, make, model, price) values (327, 'Cadillac', 'Escalade ESV', '¥0.26');
insert into car (id, make, model, price) values (328, 'Pontiac', 'Vibe', '¥0.44');
insert into car (id, make, model, price) values (329, 'Mazda', 'Miata MX-5', '¥2.66');
insert into car (id, make, model, price) values (330, 'Chevrolet', 'Citation', '¥4.46');
insert into car (id, make, model, price) values (331, 'Ford', 'Edge', '¥8.44');
insert into car (id, make, model, price) values (332, 'Hyundai', 'Genesis', '¥5.75');
insert into car (id, make, model, price) values (333, 'Mercury', 'Mystique', '¥9.78');
insert into car (id, make, model, price) values (334, 'GMC', 'Sonoma', '¥7.53');
insert into car (id, make, model, price) values (335, 'Acura', 'NSX', '¥5.46');
insert into car (id, make, model, price) values (336, 'Audi', '5000S', '¥9.55');
insert into car (id, make, model, price) values (337, 'Suzuki', 'XL7', '¥6.05');
insert into car (id, make, model, price) values (338, 'Ford', 'Transit Connect', '¥2.90');
insert into car (id, make, model, price) values (339, 'Mitsubishi', 'Galant', '¥2.83');
insert into car (id, make, model, price) values (340, 'Toyota', 'Land Cruiser', '¥2.33');
insert into car (id, make, model, price) values (341, 'Mercedes-Benz', 'C-Class', '¥6.44');
insert into car (id, make, model, price) values (342, 'Maserati', 'Biturbo', '¥0.58');
insert into car (id, make, model, price) values (343, 'Mazda', '626', '¥6.64');
insert into car (id, make, model, price) values (344, 'Mitsubishi', 'Montero', '¥2.46');
insert into car (id, make, model, price) values (345, 'Pontiac', 'Grand Am', '¥2.05');
insert into car (id, make, model, price) values (346, 'Chevrolet', 'Monte Carlo', '¥6.73');
insert into car (id, make, model, price) values (347, 'Mitsubishi', 'Tredia', '¥9.37');
insert into car (id, make, model, price) values (348, 'BMW', '760', '¥6.14');
insert into car (id, make, model, price) values (349, 'Honda', 'Pilot', '¥0.59');
insert into car (id, make, model, price) values (350, 'Suzuki', 'XL-7', '¥1.88');
insert into car (id, make, model, price) values (351, 'Chevrolet', 'Corvette', '¥9.96');
insert into car (id, make, model, price) values (352, 'Mercedes-Benz', 'S-Class', '¥2.36');
insert into car (id, make, model, price) values (353, 'Ford', 'F350', '¥6.23');
insert into car (id, make, model, price) values (354, 'Mitsubishi', 'Mirage', '¥0.84');
insert into car (id, make, model, price) values (355, 'Mercedes-Benz', 'C-Class', '¥8.11');
insert into car (id, make, model, price) values (356, 'Chrysler', '200', '¥6.45');
insert into car (id, make, model, price) values (357, 'Audi', 'A6', '¥1.08');
insert into car (id, make, model, price) values (358, 'Audi', '5000S', '¥1.19');
insert into car (id, make, model, price) values (359, 'Dodge', 'Intrepid', '¥9.53');
insert into car (id, make, model, price) values (360, 'Chevrolet', 'Corvette', '¥3.68');
insert into car (id, make, model, price) values (361, 'Jeep', 'Grand Cherokee', '¥7.37');
insert into car (id, make, model, price) values (362, 'Foose', 'Hemisfear', '¥9.99');
insert into car (id, make, model, price) values (363, 'Acura', 'TL', '¥4.01');
insert into car (id, make, model, price) values (364, 'Subaru', 'Legacy', '¥0.47');
insert into car (id, make, model, price) values (365, 'Ford', 'Excursion', '¥6.42');
insert into car (id, make, model, price) values (366, 'Pontiac', 'Bonneville', '¥1.09');
insert into car (id, make, model, price) values (367, 'Toyota', 'Prius c', '¥3.07');
insert into car (id, make, model, price) values (368, 'Mazda', 'B2600', '¥3.58');
insert into car (id, make, model, price) values (369, 'BMW', '545', '¥3.94');
insert into car (id, make, model, price) values (370, 'Volkswagen', 'GTI', '¥4.93');
insert into car (id, make, model, price) values (371, 'Toyota', 'Highlander', '¥3.77');
insert into car (id, make, model, price) values (372, 'Toyota', 'Paseo', '¥3.25');
insert into car (id, make, model, price) values (373, 'Audi', 'A6', '¥2.77');
insert into car (id, make, model, price) values (374, 'Chevrolet', 'Express 1500', '¥8.81');
insert into car (id, make, model, price) values (375, 'GMC', 'Yukon Denali', '¥7.78');
insert into car (id, make, model, price) values (376, 'Buick', 'LaCrosse', '¥9.99');
insert into car (id, make, model, price) values (377, 'Subaru', 'Legacy', '¥3.54');
insert into car (id, make, model, price) values (378, 'Subaru', 'B9 Tribeca', '¥7.96');
insert into car (id, make, model, price) values (379, 'Subaru', 'Tribeca', '¥0.44');
insert into car (id, make, model, price) values (380, 'Volkswagen', 'Passat', '¥7.58');
insert into car (id, make, model, price) values (381, 'Toyota', 'Xtra', '¥0.12');
insert into car (id, make, model, price) values (382, 'Subaru', 'Impreza WRX', '¥8.88');
insert into car (id, make, model, price) values (383, 'Acura', 'TSX', '¥5.72');
insert into car (id, make, model, price) values (384, 'Buick', 'Rainier', '¥2.73');
insert into car (id, make, model, price) values (385, 'Kia', 'Optima', '¥8.13');
insert into car (id, make, model, price) values (386, 'Mercedes-Benz', 'M-Class', '¥4.82');
insert into car (id, make, model, price) values (387, 'Volvo', 'S40', '¥6.70');
insert into car (id, make, model, price) values (388, 'Acura', 'NSX', '¥1.00');
insert into car (id, make, model, price) values (389, 'Plymouth', 'Grand Voyager', '¥6.56');
insert into car (id, make, model, price) values (390, 'Mitsubishi', 'Cordia', '¥9.13');
insert into car (id, make, model, price) values (391, 'BMW', '5 Series', '¥5.12');
insert into car (id, make, model, price) values (392, 'Lincoln', 'Town Car', '¥8.04');
insert into car (id, make, model, price) values (393, 'Suzuki', 'Grand Vitara', '¥4.05');
insert into car (id, make, model, price) values (394, 'Ford', 'Expedition', '¥6.83');
insert into car (id, make, model, price) values (395, 'Nissan', 'Pathfinder', '¥7.34');
insert into car (id, make, model, price) values (396, 'Isuzu', 'i-350', '¥1.25');
insert into car (id, make, model, price) values (397, 'Honda', 'del Sol', '¥9.38');
insert into car (id, make, model, price) values (398, 'Mazda', 'Tribute', '¥2.47');
insert into car (id, make, model, price) values (399, 'Ford', 'Flex', '¥8.37');
insert into car (id, make, model, price) values (400, 'Volkswagen', 'Fox', '¥6.52');
insert into car (id, make, model, price) values (401, 'Porsche', '924', '¥0.74');
insert into car (id, make, model, price) values (402, 'Mazda', 'B-Series Plus', '¥5.43');
insert into car (id, make, model, price) values (403, 'Ford', 'Escort', '¥4.91');
insert into car (id, make, model, price) values (404, 'Volkswagen', 'GTI', '¥8.03');
insert into car (id, make, model, price) values (405, 'Ford', 'Expedition EL', '¥1.82');
insert into car (id, make, model, price) values (406, 'Ford', 'Bronco', '¥2.84');
insert into car (id, make, model, price) values (407, 'Mercedes-Benz', 'SL-Class', '¥2.79');
insert into car (id, make, model, price) values (408, 'Subaru', 'Legacy', '¥8.42');
insert into car (id, make, model, price) values (409, 'Ford', 'Escort', '¥6.98');
insert into car (id, make, model, price) values (410, 'Hyundai', 'Elantra', '¥3.21');
insert into car (id, make, model, price) values (411, 'Isuzu', 'Space', '¥3.33');
insert into car (id, make, model, price) values (412, 'Ford', 'F150', '¥8.23');
insert into car (id, make, model, price) values (413, 'Buick', 'Century', '¥8.21');
insert into car (id, make, model, price) values (414, 'Dodge', 'Grand Caravan', '¥8.43');
insert into car (id, make, model, price) values (415, 'Chevrolet', 'Equinox', '¥7.23');
insert into car (id, make, model, price) values (416, 'Mitsubishi', 'Montero Sport', '¥6.53');
insert into car (id, make, model, price) values (417, 'Volvo', 'S90', '¥2.39');
insert into car (id, make, model, price) values (418, 'Plymouth', 'Prowler', '¥3.51');
insert into car (id, make, model, price) values (419, 'Jaguar', 'XK Series', '¥0.86');
insert into car (id, make, model, price) values (420, 'Mercury', 'Grand Marquis', '¥3.87');
insert into car (id, make, model, price) values (421, 'Dodge', 'Ram 1500 Club', '¥7.00');
insert into car (id, make, model, price) values (422, 'Chevrolet', 'Suburban 1500', '¥8.13');
insert into car (id, make, model, price) values (423, 'Honda', 'S2000', '¥9.17');
insert into car (id, make, model, price) values (424, 'Volkswagen', 'Eurovan', '¥2.69');
insert into car (id, make, model, price) values (425, 'Dodge', 'Viper', '¥5.97');
insert into car (id, make, model, price) values (426, 'Ford', 'F450', '¥5.82');
insert into car (id, make, model, price) values (427, 'Oldsmobile', 'Silhouette', '¥0.07');
insert into car (id, make, model, price) values (428, 'Mercury', 'Villager', '¥1.01');
insert into car (id, make, model, price) values (429, 'Saturn', 'VUE', '¥5.23');
insert into car (id, make, model, price) values (430, 'Mazda', 'MX-3', '¥1.79');
insert into car (id, make, model, price) values (431, 'Volvo', 'S60', '¥6.69');
insert into car (id, make, model, price) values (432, 'Pontiac', 'Grand Am', '¥0.39');
insert into car (id, make, model, price) values (433, 'GMC', '3500 Club Coupe', '¥8.27');
insert into car (id, make, model, price) values (434, 'Audi', 'TT', '¥9.80');
insert into car (id, make, model, price) values (435, 'MG', 'MGB', '¥9.94');
insert into car (id, make, model, price) values (436, 'Ford', 'E250', '¥7.80');
insert into car (id, make, model, price) values (437, 'GMC', '3500 Club Coupe', '¥8.89');
insert into car (id, make, model, price) values (438, 'Plymouth', 'Sundance', '¥8.55');
insert into car (id, make, model, price) values (439, 'Chevrolet', 'Monte Carlo', '¥8.30');
insert into car (id, make, model, price) values (440, 'Chevrolet', '1500', '¥9.56');
insert into car (id, make, model, price) values (441, 'Jaguar', 'S-Type', '¥5.00');
insert into car (id, make, model, price) values (442, 'Mercedes-Benz', 'W201', '¥0.62');
insert into car (id, make, model, price) values (443, 'Cadillac', 'Catera', '¥9.73');
insert into car (id, make, model, price) values (444, 'Lincoln', 'LS', '¥4.18');
insert into car (id, make, model, price) values (445, 'Chevrolet', 'Suburban 2500', '¥9.20');
insert into car (id, make, model, price) values (446, 'Chevrolet', 'Camaro', '¥6.12');
insert into car (id, make, model, price) values (447, 'Subaru', 'Justy', '¥8.11');
insert into car (id, make, model, price) values (448, 'Hyundai', 'Genesis Coupe', '¥1.28');
insert into car (id, make, model, price) values (449, 'Dodge', 'Avenger', '¥1.27');
insert into car (id, make, model, price) values (450, 'Aston Martin', 'DBS', '¥0.33');
insert into car (id, make, model, price) values (451, 'Chrysler', 'LHS', '¥3.85');
insert into car (id, make, model, price) values (452, 'Pontiac', 'Sunbird', '¥2.65');
insert into car (id, make, model, price) values (453, 'Mercedes-Benz', 'G-Class', '¥0.49');
insert into car (id, make, model, price) values (454, 'Buick', 'Hearse', '¥0.41');
insert into car (id, make, model, price) values (455, 'Buick', 'Electra', '¥5.25');
insert into car (id, make, model, price) values (456, 'Kia', 'Sorento', '¥6.39');
insert into car (id, make, model, price) values (457, 'Chevrolet', 'Tahoe', '¥5.09');
insert into car (id, make, model, price) values (458, 'Jaguar', 'XJ', '¥3.56');
insert into car (id, make, model, price) values (459, 'Mazda', '323', '¥1.18');
insert into car (id, make, model, price) values (460, 'Ford', 'Fairlane', '¥8.92');
insert into car (id, make, model, price) values (461, 'Pontiac', 'GTO', '¥6.01');
insert into car (id, make, model, price) values (462, 'GMC', 'Yukon XL 1500', '¥2.74');
insert into car (id, make, model, price) values (463, 'Mitsubishi', 'Galant', '¥8.26');
insert into car (id, make, model, price) values (464, 'Chevrolet', 'Corsica', '¥2.71');
insert into car (id, make, model, price) values (465, 'Lincoln', 'Town Car', '¥7.20');
insert into car (id, make, model, price) values (466, 'Hyundai', 'Excel', '¥8.93');
insert into car (id, make, model, price) values (467, 'Volvo', 'V70', '¥9.93');
insert into car (id, make, model, price) values (468, 'Chevrolet', 'S10 Blazer', '¥4.63');
insert into car (id, make, model, price) values (469, 'Audi', 'A4', '¥4.48');
insert into car (id, make, model, price) values (470, 'BMW', 'X3', '¥0.90');
insert into car (id, make, model, price) values (471, 'Suzuki', 'Forenza', '¥4.65');
insert into car (id, make, model, price) values (472, 'Nissan', 'Titan', '¥9.41');
insert into car (id, make, model, price) values (473, 'Chevrolet', 'Blazer', '¥3.77');
insert into car (id, make, model, price) values (474, 'Suzuki', 'X-90', '¥2.03');
insert into car (id, make, model, price) values (475, 'Lincoln', 'Town Car', '¥5.17');
insert into car (id, make, model, price) values (476, 'Mazda', 'Miata MX-5', '¥4.19');
insert into car (id, make, model, price) values (477, 'Acura', 'Integra', '¥1.93');
insert into car (id, make, model, price) values (478, 'Saturn', 'S-Series', '¥1.36');
insert into car (id, make, model, price) values (479, 'Maybach', '57', '¥2.48');
insert into car (id, make, model, price) values (480, 'Toyota', 'Celica', '¥3.76');
insert into car (id, make, model, price) values (481, 'Pontiac', 'Bonneville', '¥8.14');
insert into car (id, make, model, price) values (482, 'Mercury', 'Grand Marquis', '¥2.33');
insert into car (id, make, model, price) values (483, 'Ford', 'Ranger', '¥7.57');
insert into car (id, make, model, price) values (484, 'Mazda', 'MX-3', '¥8.09');
insert into car (id, make, model, price) values (485, 'Subaru', 'Tribeca', '¥6.55');
insert into car (id, make, model, price) values (486, 'Nissan', '200SX', '¥1.48');
insert into car (id, make, model, price) values (487, 'Chevrolet', 'Express 1500', '¥8.55');
insert into car (id, make, model, price) values (488, 'Land Rover', 'Range Rover Evoque', '¥8.57');
insert into car (id, make, model, price) values (489, 'Suzuki', 'Equator', '¥9.60');
insert into car (id, make, model, price) values (490, 'Toyota', 'Camry', '¥7.40');
insert into car (id, make, model, price) values (491, 'Land Rover', 'Discovery', '¥1.90');
insert into car (id, make, model, price) values (492, 'Mercury', 'Topaz', '¥9.59');
insert into car (id, make, model, price) values (493, 'Mazda', '626', '¥6.61');
insert into car (id, make, model, price) values (494, 'Pontiac', 'Grand Prix', '¥0.65');
insert into car (id, make, model, price) values (495, 'Toyota', 'RAV4', '¥3.22');
insert into car (id, make, model, price) values (496, 'Mitsubishi', 'Truck', '¥0.74');
insert into car (id, make, model, price) values (497, 'Mazda', 'MPV', '¥3.50');
insert into car (id, make, model, price) values (498, 'Hyundai', 'Tucson', '¥9.38');
insert into car (id, make, model, price) values (499, 'Porsche', 'Cayenne', '¥6.55');
insert into car (id, make, model, price) values (500, 'Dodge', 'Caravan', '¥6.18');
insert into car (id, make, model, price) values (501, 'Dodge', 'Ram 3500', '¥7.07');
insert into car (id, make, model, price) values (502, 'Lexus', 'GX', '¥5.28');
insert into car (id, make, model, price) values (503, 'Ford', 'LTD', '¥2.10');
insert into car (id, make, model, price) values (504, 'Isuzu', 'i-Series', '¥3.14');
insert into car (id, make, model, price) values (505, 'Infiniti', 'Q', '¥0.59');
insert into car (id, make, model, price) values (506, 'Nissan', 'Sentra', '¥4.64');
insert into car (id, make, model, price) values (507, 'Saab', '900', '¥4.59');
insert into car (id, make, model, price) values (508, 'Hyundai', 'Elantra', '¥0.31');
insert into car (id, make, model, price) values (509, 'Ford', 'Transit Connect', '¥5.87');
insert into car (id, make, model, price) values (510, 'Audi', 'TT', '¥0.46');
insert into car (id, make, model, price) values (511, 'Infiniti', 'EX', '¥0.35');
insert into car (id, make, model, price) values (512, 'Volkswagen', 'New Beetle', '¥5.37');
insert into car (id, make, model, price) values (513, 'Dodge', 'Stratus', '¥2.95');
insert into car (id, make, model, price) values (514, 'Toyota', '4Runner', '¥6.45');
insert into car (id, make, model, price) values (515, 'Lincoln', 'Aviator', '¥7.71');
insert into car (id, make, model, price) values (516, 'Buick', 'Lucerne', '¥5.74');
insert into car (id, make, model, price) values (517, 'Toyota', 'Previa', '¥4.79');
insert into car (id, make, model, price) values (518, 'Daewoo', 'Lanos', '¥4.26');
insert into car (id, make, model, price) values (519, 'Ford', 'Club Wagon', '¥1.36');
insert into car (id, make, model, price) values (520, 'Kia', 'Sedona', '¥5.48');
insert into car (id, make, model, price) values (521, 'Honda', 'Civic', '¥8.46');
insert into car (id, make, model, price) values (522, 'Aston Martin', 'DB9', '¥7.61');
insert into car (id, make, model, price) values (523, 'Chevrolet', 'Suburban 1500', '¥6.34');
insert into car (id, make, model, price) values (524, 'Mercury', 'Cougar', '¥8.33');
insert into car (id, make, model, price) values (525, 'Mercury', 'Villager', '¥3.94');
insert into car (id, make, model, price) values (526, 'MINI', 'MINI', '¥4.85');
insert into car (id, make, model, price) values (527, 'GMC', 'Sonoma', '¥8.34');
insert into car (id, make, model, price) values (528, 'GMC', 'Sonoma Club Coupe', '¥9.82');
insert into car (id, make, model, price) values (529, 'Morgan', 'Aero 8', '¥1.12');
insert into car (id, make, model, price) values (530, 'Toyota', 'Sienna', '¥6.08');
insert into car (id, make, model, price) values (531, 'Ford', 'Ranger', '¥3.92');
insert into car (id, make, model, price) values (532, 'Volvo', 'XC90', '¥6.40');
insert into car (id, make, model, price) values (533, 'Chrysler', 'Pacifica', '¥0.68');
insert into car (id, make, model, price) values (534, 'Toyota', 'Sequoia', '¥5.78');
insert into car (id, make, model, price) values (535, 'Ford', 'Focus', '¥0.96');
insert into car (id, make, model, price) values (536, 'Mitsubishi', 'Eclipse', '¥3.48');
insert into car (id, make, model, price) values (537, 'Mercury', 'Sable', '¥8.97');
insert into car (id, make, model, price) values (538, 'Mazda', 'CX-7', '¥4.23');
insert into car (id, make, model, price) values (539, 'Toyota', 'Sequoia', '¥8.39');
insert into car (id, make, model, price) values (540, 'Chevrolet', 'S10 Blazer', '¥3.45');
insert into car (id, make, model, price) values (541, 'Pontiac', 'LeMans', '¥2.81');
insert into car (id, make, model, price) values (542, 'Suzuki', 'Grand Vitara', '¥2.37');
insert into car (id, make, model, price) values (543, 'Hyundai', 'Elantra', '¥8.82');
insert into car (id, make, model, price) values (544, 'Acura', 'RSX', '¥8.42');
insert into car (id, make, model, price) values (545, 'Chevrolet', 'Beretta', '¥0.06');
insert into car (id, make, model, price) values (546, 'Chrysler', 'Crossfire', '¥8.84');
insert into car (id, make, model, price) values (547, 'Isuzu', 'Trooper', '¥9.49');
insert into car (id, make, model, price) values (548, 'BMW', '745', '¥0.95');
insert into car (id, make, model, price) values (549, 'Land Rover', 'Range Rover', '¥4.35');
insert into car (id, make, model, price) values (550, 'Mercury', 'Grand Marquis', '¥1.93');
insert into car (id, make, model, price) values (551, 'Pontiac', 'Firefly', '¥9.26');
insert into car (id, make, model, price) values (552, 'Kia', 'Rio', '¥8.08');
insert into car (id, make, model, price) values (553, 'Nissan', '350Z', '¥9.29');
insert into car (id, make, model, price) values (554, 'Chevrolet', 'Monte Carlo', '¥2.34');
insert into car (id, make, model, price) values (555, 'GMC', 'Sierra 3500', '¥6.67');
insert into car (id, make, model, price) values (556, 'Chevrolet', '1500', '¥8.16');
insert into car (id, make, model, price) values (557, 'Ford', 'Club Wagon', '¥7.23');
insert into car (id, make, model, price) values (558, 'Mazda', 'GLC', '¥1.76');
insert into car (id, make, model, price) values (559, 'Mitsubishi', 'Eclipse', '¥5.93');
insert into car (id, make, model, price) values (560, 'Chevrolet', 'Express 1500', '¥2.85');
insert into car (id, make, model, price) values (561, 'GMC', 'Yukon XL 2500', '¥8.30');
insert into car (id, make, model, price) values (562, 'Nissan', 'NV3500', '¥3.40');
insert into car (id, make, model, price) values (563, 'Ford', 'Ranger', '¥4.80');
insert into car (id, make, model, price) values (564, 'Chevrolet', 'Camaro', '¥5.16');
insert into car (id, make, model, price) values (565, 'Chrysler', 'Imperial', '¥0.38');
insert into car (id, make, model, price) values (566, 'Porsche', 'Panamera', '¥5.68');
insert into car (id, make, model, price) values (567, 'Volkswagen', 'Fox', '¥9.14');
insert into car (id, make, model, price) values (568, 'BMW', 'M3', '¥7.63');
insert into car (id, make, model, price) values (569, 'Cadillac', 'Eldorado', '¥8.85');
insert into car (id, make, model, price) values (570, 'Toyota', 'Cressida', '¥0.40');
insert into car (id, make, model, price) values (571, 'Hyundai', 'Elantra', '¥8.77');
insert into car (id, make, model, price) values (572, 'BMW', '7 Series', '¥8.38');
insert into car (id, make, model, price) values (573, 'Audi', 'A3', '¥8.99');
insert into car (id, make, model, price) values (574, 'Audi', 'Quattro', '¥4.78');
insert into car (id, make, model, price) values (575, 'Kia', 'Amanti', '¥0.07');
insert into car (id, make, model, price) values (576, 'Volvo', 'C70', '¥6.26');
insert into car (id, make, model, price) values (577, 'Honda', 'CR-X', '¥0.57');
insert into car (id, make, model, price) values (578, 'Dodge', 'Dakota', '¥9.11');
insert into car (id, make, model, price) values (579, 'Audi', 'A4', '¥1.10');
insert into car (id, make, model, price) values (580, 'Merkur', 'XR4Ti', '¥2.36');
insert into car (id, make, model, price) values (581, 'Honda', 'Civic', '¥3.93');
insert into car (id, make, model, price) values (582, 'Volkswagen', 'Eurovan', '¥6.48');
insert into car (id, make, model, price) values (583, 'Pontiac', 'Grand Prix', '¥4.46');
insert into car (id, make, model, price) values (584, 'Chevrolet', 'Suburban 1500', '¥7.47');
insert into car (id, make, model, price) values (585, 'Volkswagen', 'Touareg 2', '¥3.48');
insert into car (id, make, model, price) values (586, 'Volkswagen', 'Scirocco', '¥8.18');
insert into car (id, make, model, price) values (587, 'Dodge', 'Dakota Club', '¥9.01');
insert into car (id, make, model, price) values (588, 'Suzuki', 'Forenza', '¥4.74');
insert into car (id, make, model, price) values (589, 'Dodge', 'Ram 1500 Club', '¥4.18');
insert into car (id, make, model, price) values (590, 'Chevrolet', 'Blazer', '¥1.66');
insert into car (id, make, model, price) values (591, 'Buick', 'Park Avenue', '¥1.19');
insert into car (id, make, model, price) values (592, 'Chevrolet', 'Impala', '¥8.20');
insert into car (id, make, model, price) values (593, 'Ford', 'Expedition', '¥9.52');
insert into car (id, make, model, price) values (594, 'Volkswagen', 'GTI', '¥2.02');
insert into car (id, make, model, price) values (595, 'Lincoln', 'Blackwood', '¥8.70');
insert into car (id, make, model, price) values (596, 'Honda', 'Insight', '¥0.94');
insert into car (id, make, model, price) values (597, 'Infiniti', 'M', '¥6.74');
insert into car (id, make, model, price) values (598, 'Suzuki', 'SJ', '¥6.12');
insert into car (id, make, model, price) values (599, 'Mercedes-Benz', 'C-Class', '¥5.54');
insert into car (id, make, model, price) values (600, 'Nissan', 'Pathfinder', '¥0.85');
insert into car (id, make, model, price) values (601, 'BMW', '8 Series', '¥2.60');
insert into car (id, make, model, price) values (602, 'Nissan', 'Pathfinder Armada', '¥8.11');
insert into car (id, make, model, price) values (603, 'Volkswagen', 'New Beetle', '¥9.03');
insert into car (id, make, model, price) values (604, 'Saab', '900', '¥5.72');
insert into car (id, make, model, price) values (605, 'Chevrolet', 'G-Series G10', '¥2.59');
insert into car (id, make, model, price) values (606, 'Lotus', 'Esprit', '¥8.63');
insert into car (id, make, model, price) values (607, 'Volvo', '940', '¥5.33');
insert into car (id, make, model, price) values (608, 'Toyota', 'RAV4', '¥8.07');
insert into car (id, make, model, price) values (609, 'Suzuki', 'Grand Vitara', '¥1.58');
insert into car (id, make, model, price) values (610, 'Dodge', 'Sprinter', '¥5.15');
insert into car (id, make, model, price) values (611, 'Acura', 'TL', '¥7.89');
insert into car (id, make, model, price) values (612, 'Volkswagen', 'rio', '¥9.54');
insert into car (id, make, model, price) values (613, 'Mazda', 'Millenia', '¥5.89');
insert into car (id, make, model, price) values (614, 'Oldsmobile', 'Aurora', '¥8.69');
insert into car (id, make, model, price) values (615, 'Infiniti', 'G', '¥6.95');
insert into car (id, make, model, price) values (616, 'Lincoln', 'Zephyr', '¥7.61');
insert into car (id, make, model, price) values (617, 'GMC', 'Suburban 2500', '¥9.45');
insert into car (id, make, model, price) values (618, 'Chevrolet', 'Suburban 2500', '¥3.56');
insert into car (id, make, model, price) values (619, 'Porsche', '944', '¥8.98');
insert into car (id, make, model, price) values (620, 'Kia', 'Spectra', '¥3.47');
insert into car (id, make, model, price) values (621, 'Pontiac', 'Bonneville', '¥4.19');
insert into car (id, make, model, price) values (622, 'Pontiac', 'G3', '¥4.52');
insert into car (id, make, model, price) values (623, 'Chevrolet', 'Express 2500', '¥2.56');
insert into car (id, make, model, price) values (624, 'Chevrolet', 'Colorado', '¥0.72');
insert into car (id, make, model, price) values (625, 'Dodge', 'Grand Caravan', '¥5.00');
insert into car (id, make, model, price) values (626, 'Subaru', 'Impreza WRX', '¥9.41');
insert into car (id, make, model, price) values (627, 'Nissan', 'GT-R', '¥9.70');
insert into car (id, make, model, price) values (628, 'Dodge', 'Durango', '¥5.47');
insert into car (id, make, model, price) values (629, 'Dodge', 'Sprinter', '¥6.83');
insert into car (id, make, model, price) values (630, 'Dodge', 'Aries', '¥9.30');
insert into car (id, make, model, price) values (631, 'Subaru', 'Tribeca', '¥4.60');
insert into car (id, make, model, price) values (632, 'Lincoln', 'Town Car', '¥2.44');
insert into car (id, make, model, price) values (633, 'Dodge', 'Charger', '¥1.39');
insert into car (id, make, model, price) values (634, 'Mazda', 'Mazda6', '¥2.81');
insert into car (id, make, model, price) values (635, 'Dodge', 'Aspen', '¥4.50');
insert into car (id, make, model, price) values (636, 'Mitsubishi', 'GTO', '¥3.24');
insert into car (id, make, model, price) values (637, 'Aston Martin', 'V12 Vantage', '¥0.77');
insert into car (id, make, model, price) values (638, 'Mitsubishi', 'Endeavor', '¥2.74');
insert into car (id, make, model, price) values (639, 'Chevrolet', 'Corvette', '¥0.69');
insert into car (id, make, model, price) values (640, 'Pontiac', 'Firefly', '¥4.64');
insert into car (id, make, model, price) values (641, 'Suzuki', 'Samurai', '¥6.17');
insert into car (id, make, model, price) values (642, 'BMW', '6 Series', '¥1.26');
insert into car (id, make, model, price) values (643, 'Volkswagen', 'GTI', '¥6.13');
insert into car (id, make, model, price) values (644, 'Acura', 'TL', '¥4.25');
insert into car (id, make, model, price) values (645, 'Kia', 'Optima', '¥4.24');
insert into car (id, make, model, price) values (646, 'Mitsubishi', 'Chariot', '¥2.18');
insert into car (id, make, model, price) values (647, 'Ferrari', 'FF', '¥9.72');
insert into car (id, make, model, price) values (648, 'Subaru', 'Outback', '¥4.82');
insert into car (id, make, model, price) values (649, 'Lamborghini', 'Aventador', '¥2.31');
insert into car (id, make, model, price) values (650, 'Ford', 'Explorer', '¥2.17');
insert into car (id, make, model, price) values (651, 'Audi', '5000S', '¥3.79');
insert into car (id, make, model, price) values (652, 'Chevrolet', 'Express 3500', '¥2.95');
insert into car (id, make, model, price) values (653, 'Chrysler', 'Concorde', '¥7.09');
insert into car (id, make, model, price) values (654, 'GMC', 'Envoy', '¥2.83');
insert into car (id, make, model, price) values (655, 'Ford', 'Taurus', '¥9.26');
insert into car (id, make, model, price) values (656, 'Aptera', 'Type-1h', '¥8.82');
insert into car (id, make, model, price) values (657, 'Saturn', 'Relay', '¥6.45');
insert into car (id, make, model, price) values (658, 'Aptera', '2e', '¥8.02');
insert into car (id, make, model, price) values (659, 'Infiniti', 'QX', '¥9.37');
insert into car (id, make, model, price) values (660, 'Chevrolet', 'Silverado 2500', '¥9.33');
insert into car (id, make, model, price) values (661, 'Mercedes-Benz', 'E-Class', '¥6.52');
insert into car (id, make, model, price) values (662, 'Chevrolet', 'Corvette', '¥4.12');
insert into car (id, make, model, price) values (663, 'Ford', 'Fusion', '¥3.13');
insert into car (id, make, model, price) values (664, 'Lexus', 'IS-F', '¥7.97');
insert into car (id, make, model, price) values (665, 'Mercedes-Benz', 'M-Class', '¥3.34');
insert into car (id, make, model, price) values (666, 'Pontiac', 'GTO', '¥5.03');
insert into car (id, make, model, price) values (667, 'Panoz', 'Esperante', '¥9.85');
insert into car (id, make, model, price) values (668, 'Nissan', 'Titan', '¥7.48');
insert into car (id, make, model, price) values (669, 'Toyota', 'Previa', '¥9.56');
insert into car (id, make, model, price) values (670, 'Subaru', 'Impreza', '¥0.83');
insert into car (id, make, model, price) values (671, 'Oldsmobile', 'Achieva', '¥5.48');
insert into car (id, make, model, price) values (672, 'Mercedes-Benz', '300TE', '¥3.20');
insert into car (id, make, model, price) values (673, 'Volvo', 'V50', '¥7.27');
insert into car (id, make, model, price) values (674, 'Toyota', 'Highlander', '¥6.77');
insert into car (id, make, model, price) values (675, 'Infiniti', 'J', '¥8.11');
insert into car (id, make, model, price) values (676, 'Chevrolet', 'Silverado 1500', '¥8.92');
insert into car (id, make, model, price) values (677, 'Ford', 'Expedition', '¥7.12');
insert into car (id, make, model, price) values (678, 'Toyota', '4Runner', '¥3.71');
insert into car (id, make, model, price) values (679, 'Subaru', 'Forester', '¥6.12');
insert into car (id, make, model, price) values (680, 'GMC', 'Sierra 3500HD', '¥2.47');
insert into car (id, make, model, price) values (681, 'Pontiac', 'Fiero', '¥0.00');
insert into car (id, make, model, price) values (682, 'Hummer', 'H1', '¥0.43');
insert into car (id, make, model, price) values (683, 'Volvo', 'XC90', '¥7.71');
insert into car (id, make, model, price) values (684, 'Nissan', 'Pathfinder', '¥3.22');
insert into car (id, make, model, price) values (685, 'GMC', 'Sierra 3500', '¥1.56');
insert into car (id, make, model, price) values (686, 'Kia', 'Spectra', '¥2.22');
insert into car (id, make, model, price) values (687, 'Lamborghini', 'Countach', '¥8.50');
insert into car (id, make, model, price) values (688, 'Dodge', 'Ram Van B150', '¥0.57');
insert into car (id, make, model, price) values (689, 'GMC', 'Yukon XL 2500', '¥7.39');
insert into car (id, make, model, price) values (690, 'Scion', 'tC', '¥5.21');
insert into car (id, make, model, price) values (691, 'GMC', 'Sierra 2500', '¥5.67');
insert into car (id, make, model, price) values (692, 'Ford', 'Econoline E350', '¥3.47');
insert into car (id, make, model, price) values (693, 'Volkswagen', 'Passat', '¥3.83');
insert into car (id, make, model, price) values (694, 'Toyota', 'T100 Xtra', '¥9.87');
insert into car (id, make, model, price) values (695, 'Ford', 'F350', '¥6.79');
insert into car (id, make, model, price) values (696, 'Smart', 'Fortwo', '¥9.92');
insert into car (id, make, model, price) values (697, 'Lotus', 'Esprit', '¥3.60');
insert into car (id, make, model, price) values (698, 'Lexus', 'LX', '¥1.27');
insert into car (id, make, model, price) values (699, 'Chevrolet', 'Malibu', '¥0.86');
insert into car (id, make, model, price) values (700, 'BMW', 'M', '¥6.50');
insert into car (id, make, model, price) values (701, 'Chevrolet', '1500', '¥0.76');
insert into car (id, make, model, price) values (702, 'BMW', 'X6', '¥7.72');
insert into car (id, make, model, price) values (703, 'Hyundai', 'Elantra', '¥9.91');
insert into car (id, make, model, price) values (704, 'Mazda', 'Millenia', '¥1.70');
insert into car (id, make, model, price) values (705, 'Oldsmobile', 'Silhouette', '¥1.46');
insert into car (id, make, model, price) values (706, 'Chevrolet', 'Impala', '¥0.72');
insert into car (id, make, model, price) values (707, 'Dodge', 'Dakota', '¥2.23');
insert into car (id, make, model, price) values (708, 'Ford', 'Taurus', '¥7.28');
insert into car (id, make, model, price) values (709, 'Chevrolet', 'Metro', '¥7.86');
insert into car (id, make, model, price) values (710, 'Chevrolet', 'Impala', '¥0.55');
insert into car (id, make, model, price) values (711, 'Acura', 'RSX', '¥9.30');
insert into car (id, make, model, price) values (712, 'Nissan', 'Pathfinder', '¥0.73');
insert into car (id, make, model, price) values (713, 'Chrysler', 'New Yorker', '¥5.47');
insert into car (id, make, model, price) values (714, 'Jaguar', 'XK', '¥3.57');
insert into car (id, make, model, price) values (715, 'Mitsubishi', 'Pajero', '¥5.93');
insert into car (id, make, model, price) values (716, 'Aston Martin', 'Vantage', '¥7.72');
insert into car (id, make, model, price) values (717, 'Mercedes-Benz', 'S-Class', '¥9.17');
insert into car (id, make, model, price) values (718, 'Porsche', '911', '¥8.98');
insert into car (id, make, model, price) values (719, 'Volkswagen', 'Corrado', '¥7.68');
insert into car (id, make, model, price) values (720, 'Oldsmobile', 'Bravada', '¥5.33');
insert into car (id, make, model, price) values (721, 'Dodge', 'Dakota Club', '¥1.92');
insert into car (id, make, model, price) values (722, 'GMC', '3500 Club Coupe', '¥0.47');
insert into car (id, make, model, price) values (723, 'Lincoln', 'LS', '¥6.75');
insert into car (id, make, model, price) values (724, 'Jaguar', 'XJ Series', '¥9.27');
insert into car (id, make, model, price) values (725, 'Pontiac', 'Grand Prix', '¥2.41');
insert into car (id, make, model, price) values (726, 'Mazda', 'MPV', '¥0.99');
insert into car (id, make, model, price) values (727, 'Acura', 'RL', '¥9.82');
insert into car (id, make, model, price) values (728, 'Plymouth', 'Colt', '¥3.95');
insert into car (id, make, model, price) values (729, 'GMC', 'Sierra 1500', '¥7.89');
insert into car (id, make, model, price) values (730, 'Infiniti', 'Q', '¥2.77');
insert into car (id, make, model, price) values (731, 'Dodge', 'Avenger', '¥8.72');
insert into car (id, make, model, price) values (732, 'Mercedes-Benz', 'E-Class', '¥7.14');
insert into car (id, make, model, price) values (733, 'Chevrolet', 'Suburban 2500', '¥6.55');
insert into car (id, make, model, price) values (734, 'Toyota', 'Avalon', '¥2.02');
insert into car (id, make, model, price) values (735, 'Chevrolet', 'Astro', '¥6.80');
insert into car (id, make, model, price) values (736, 'Dodge', 'Avenger', '¥6.90');
insert into car (id, make, model, price) values (737, 'Mitsubishi', 'Galant', '¥6.53');
insert into car (id, make, model, price) values (738, 'BMW', '3 Series', '¥5.42');
insert into car (id, make, model, price) values (739, 'Maserati', 'Quattroporte', '¥4.29');
insert into car (id, make, model, price) values (740, 'Citroën', 'CX', '¥9.53');
insert into car (id, make, model, price) values (741, 'Chevrolet', 'Sportvan G30', '¥5.70');
insert into car (id, make, model, price) values (742, 'Lincoln', 'Navigator L', '¥5.62');
insert into car (id, make, model, price) values (743, 'Ford', 'Econoline E250', '¥5.95');
insert into car (id, make, model, price) values (744, 'Mazda', 'MX-5', '¥5.57');
insert into car (id, make, model, price) values (745, 'Pontiac', 'Sunfire', '¥6.42');
insert into car (id, make, model, price) values (746, 'Ford', 'Edge', '¥2.12');
insert into car (id, make, model, price) values (747, 'Volkswagen', 'rio', '¥4.11');
insert into car (id, make, model, price) values (748, 'Lexus', 'IS-F', '¥2.71');
insert into car (id, make, model, price) values (749, 'Saab', '9000', '¥1.19');
insert into car (id, make, model, price) values (750, 'Dodge', 'Ram Van 2500', '¥5.65');
insert into car (id, make, model, price) values (751, 'Honda', 'Passport', '¥5.97');
insert into car (id, make, model, price) values (752, 'Chrysler', 'Sebring', '¥2.10');
insert into car (id, make, model, price) values (753, 'BMW', 'M3', '¥8.13');
insert into car (id, make, model, price) values (754, 'Isuzu', 'Trooper', '¥4.56');
insert into car (id, make, model, price) values (755, 'Volkswagen', 'Touareg', '¥2.77');
insert into car (id, make, model, price) values (756, 'Chevrolet', 'Silverado Hybrid', '¥8.45');
insert into car (id, make, model, price) values (757, 'Subaru', 'Alcyone SVX', '¥9.85');
insert into car (id, make, model, price) values (758, 'Toyota', 'Sienna', '¥6.12');
insert into car (id, make, model, price) values (759, 'Saturn', 'Aura', '¥3.27');
insert into car (id, make, model, price) values (760, 'Scion', 'tC', '¥8.67');
insert into car (id, make, model, price) values (761, 'Chevrolet', 'Avalanche', '¥1.70');
insert into car (id, make, model, price) values (762, 'Buick', 'Skylark', '¥5.28');
insert into car (id, make, model, price) values (763, 'Lincoln', 'Continental Mark VII', '¥4.97');
insert into car (id, make, model, price) values (764, 'Dodge', 'Caravan', '¥1.49');
insert into car (id, make, model, price) values (765, 'Ford', 'F350', '¥5.76');
insert into car (id, make, model, price) values (766, 'Ford', 'Escape', '¥7.25');
insert into car (id, make, model, price) values (767, 'Pontiac', 'GTO', '¥2.98');
insert into car (id, make, model, price) values (768, 'Chevrolet', 'Suburban', '¥2.03');
insert into car (id, make, model, price) values (769, 'Nissan', 'Altima', '¥7.45');
insert into car (id, make, model, price) values (770, 'Land Rover', 'Range Rover Sport', '¥6.01');
insert into car (id, make, model, price) values (771, 'Mercury', 'Tracer', '¥0.93');
insert into car (id, make, model, price) values (772, 'Saturn', 'S-Series', '¥6.63');
insert into car (id, make, model, price) values (773, 'Toyota', 'Highlander Hybrid', '¥3.37');
insert into car (id, make, model, price) values (774, 'Ford', 'Tempo', '¥2.64');
insert into car (id, make, model, price) values (775, 'Ford', 'F-Series', '¥0.38');
insert into car (id, make, model, price) values (776, 'BMW', '3 Series', '¥1.47');
insert into car (id, make, model, price) values (777, 'Mercury', 'Villager', '¥6.23');
insert into car (id, make, model, price) values (778, 'Ford', 'Econoline E250', '¥1.84');
insert into car (id, make, model, price) values (779, 'Nissan', 'Armada', '¥8.15');
insert into car (id, make, model, price) values (780, 'Suzuki', 'SX4', '¥2.02');
insert into car (id, make, model, price) values (781, 'Kia', 'Sedona', '¥5.64');
insert into car (id, make, model, price) values (782, 'Subaru', 'SVX', '¥1.82');
insert into car (id, make, model, price) values (783, 'Volkswagen', 'Jetta', '¥5.59');
insert into car (id, make, model, price) values (784, 'Pontiac', 'Torrent', '¥8.08');
insert into car (id, make, model, price) values (785, 'Lexus', 'ES', '¥6.83');
insert into car (id, make, model, price) values (786, 'Honda', 'Accord', '¥9.98');
insert into car (id, make, model, price) values (787, 'Land Rover', 'Defender', '¥7.40');
insert into car (id, make, model, price) values (788, 'Maybach', 'Landaulet', '¥3.95');
insert into car (id, make, model, price) values (789, 'Pontiac', 'Safari', '¥5.23');
insert into car (id, make, model, price) values (790, 'Pontiac', 'LeMans', '¥2.30');
insert into car (id, make, model, price) values (791, 'Lexus', 'IS', '¥1.58');
insert into car (id, make, model, price) values (792, 'Honda', 'CR-V', '¥6.98');
insert into car (id, make, model, price) values (793, 'Mazda', '323', '¥1.13');
insert into car (id, make, model, price) values (794, 'Hyundai', 'Elantra', '¥0.30');
insert into car (id, make, model, price) values (795, 'BMW', '525', '¥4.48');
insert into car (id, make, model, price) values (796, 'Jeep', 'Liberty', '¥5.45');
insert into car (id, make, model, price) values (797, 'Ford', 'Taurus', '¥6.57');
insert into car (id, make, model, price) values (798, 'Acura', 'RL', '¥6.82');
insert into car (id, make, model, price) values (799, 'Hyundai', 'Azera', '¥2.23');
insert into car (id, make, model, price) values (800, 'Ford', 'Model T', '¥8.70');
insert into car (id, make, model, price) values (801, 'Audi', 'A8', '¥4.36');
insert into car (id, make, model, price) values (802, 'Chevrolet', 'Avalanche 1500', '¥7.62');
insert into car (id, make, model, price) values (803, 'Ford', 'E-Series', '¥8.76');
insert into car (id, make, model, price) values (804, 'Buick', 'Century', '¥4.93');
insert into car (id, make, model, price) values (805, 'Toyota', 'Camry', '¥0.95');
insert into car (id, make, model, price) values (806, 'Maybach', '57', '¥9.18');
insert into car (id, make, model, price) values (807, 'GMC', 'Sierra 1500', '¥4.24');
insert into car (id, make, model, price) values (808, 'Acura', 'TL', '¥2.42');
insert into car (id, make, model, price) values (809, 'Mazda', 'Mazdaspeed 3', '¥7.46');
insert into car (id, make, model, price) values (810, 'Chrysler', 'Sebring', '¥9.01');
insert into car (id, make, model, price) values (811, 'Jaguar', 'XF', '¥2.38');
insert into car (id, make, model, price) values (812, 'Pontiac', 'Grand Prix', '¥8.75');
insert into car (id, make, model, price) values (813, 'Fiat', 'Nuova 500', '¥0.57');
insert into car (id, make, model, price) values (814, 'Hyundai', 'Scoupe', '¥8.11');
insert into car (id, make, model, price) values (815, 'Bentley', 'Continental', '¥2.94');
insert into car (id, make, model, price) values (816, 'GMC', 'Acadia', '¥4.03');
insert into car (id, make, model, price) values (817, 'Suzuki', 'Swift', '¥5.38');
insert into car (id, make, model, price) values (818, 'Mercedes-Benz', 'R-Class', '¥0.13');
insert into car (id, make, model, price) values (819, 'Lexus', 'GS', '¥2.14');
insert into car (id, make, model, price) values (820, 'Subaru', 'Impreza', '¥2.41');
insert into car (id, make, model, price) values (821, 'Dodge', 'Grand Caravan', '¥1.47');
insert into car (id, make, model, price) values (822, 'BMW', 'M Roadster', '¥2.49');
insert into car (id, make, model, price) values (823, 'Toyota', 'Previa', '¥8.76');
insert into car (id, make, model, price) values (824, 'Pontiac', 'Vibe', '¥3.83');
insert into car (id, make, model, price) values (825, 'Mercedes-Benz', 'SLK-Class', '¥0.12');
insert into car (id, make, model, price) values (826, 'Acura', 'RL', '¥4.99');
insert into car (id, make, model, price) values (827, 'Mercedes-Benz', 'E-Class', '¥1.59');
insert into car (id, make, model, price) values (828, 'Kia', 'Optima', '¥2.39');
insert into car (id, make, model, price) values (829, 'Dodge', 'Stealth', '¥1.59');
insert into car (id, make, model, price) values (830, 'Lotus', 'Esprit', '¥7.72');
insert into car (id, make, model, price) values (831, 'Lincoln', 'Continental Mark VII', '¥1.23');
insert into car (id, make, model, price) values (832, 'Nissan', 'Maxima', '¥4.14');
insert into car (id, make, model, price) values (833, 'Toyota', 'Tundra', '¥9.66');
insert into car (id, make, model, price) values (834, 'Mercedes-Benz', 'S-Class', '¥4.52');
insert into car (id, make, model, price) values (835, 'Infiniti', 'G', '¥4.84');
insert into car (id, make, model, price) values (836, 'Mitsubishi', 'Mirage', '¥8.40');
insert into car (id, make, model, price) values (837, 'Ferrari', 'FF', '¥9.75');
insert into car (id, make, model, price) values (838, 'Subaru', 'Alcyone SVX', '¥3.15');
insert into car (id, make, model, price) values (839, 'Ford', 'Fairlane', '¥7.88');
insert into car (id, make, model, price) values (840, 'Kia', 'Sephia', '¥1.01');
insert into car (id, make, model, price) values (841, 'Buick', 'Park Avenue', '¥3.06');
insert into car (id, make, model, price) values (842, 'Oldsmobile', 'Ciera', '¥5.12');
insert into car (id, make, model, price) values (843, 'Dodge', 'Durango', '¥6.21');
insert into car (id, make, model, price) values (844, 'Audi', 'A8', '¥0.27');
insert into car (id, make, model, price) values (845, 'Ford', 'Mustang', '¥5.79');
insert into car (id, make, model, price) values (846, 'Scion', 'tC', '¥2.47');
insert into car (id, make, model, price) values (847, 'Honda', 'Insight', '¥9.74');
insert into car (id, make, model, price) values (848, 'Audi', 'Allroad', '¥5.49');
insert into car (id, make, model, price) values (849, 'Nissan', '280ZX', '¥5.64');
insert into car (id, make, model, price) values (850, 'Mitsubishi', 'Outlander', '¥6.56');
insert into car (id, make, model, price) values (851, 'Audi', 'RS4', '¥7.69');
insert into car (id, make, model, price) values (852, 'Chevrolet', 'Blazer', '¥8.57');
insert into car (id, make, model, price) values (853, 'Jeep', 'Grand Cherokee', '¥4.97');
insert into car (id, make, model, price) values (854, 'Chevrolet', 'Aveo', '¥4.38');
insert into car (id, make, model, price) values (855, 'Chevrolet', 'G-Series G10', '¥5.75');
insert into car (id, make, model, price) values (856, 'Buick', 'Lucerne', '¥1.00');
insert into car (id, make, model, price) values (857, 'Chevrolet', 'SSR', '¥9.06');
insert into car (id, make, model, price) values (858, 'Toyota', 'RAV4', '¥4.04');
insert into car (id, make, model, price) values (859, 'Subaru', 'Justy', '¥5.95');
insert into car (id, make, model, price) values (860, 'Dodge', 'Viper', '¥2.85');
insert into car (id, make, model, price) values (861, 'Saab', '9-3', '¥7.65');
insert into car (id, make, model, price) values (862, 'Mitsubishi', 'Eclipse', '¥4.96');
insert into car (id, make, model, price) values (863, 'Mitsubishi', 'Montero', '¥0.83');
insert into car (id, make, model, price) values (864, 'Ford', 'Windstar', '¥1.59');
insert into car (id, make, model, price) values (865, 'Ford', 'LTD', '¥0.88');
insert into car (id, make, model, price) values (866, 'Kia', 'Sedona', '¥6.34');
insert into car (id, make, model, price) values (867, 'Oldsmobile', 'Silhouette', '¥6.55');
insert into car (id, make, model, price) values (868, 'Volkswagen', 'GTI', '¥9.15');
insert into car (id, make, model, price) values (869, 'Dodge', 'Ram 3500 Club', '¥1.74');
insert into car (id, make, model, price) values (870, 'Lexus', 'GS', '¥3.35');
insert into car (id, make, model, price) values (871, 'BMW', '325', '¥3.96');
insert into car (id, make, model, price) values (872, 'Pontiac', 'Gemini', '¥1.36');
insert into car (id, make, model, price) values (873, 'Ford', 'Windstar', '¥5.11');
insert into car (id, make, model, price) values (874, 'Bentley', 'Continental', '¥6.38');
insert into car (id, make, model, price) values (875, 'GMC', 'Suburban 2500', '¥4.42');
insert into car (id, make, model, price) values (876, 'Suzuki', 'Swift', '¥8.75');
insert into car (id, make, model, price) values (877, 'Cadillac', 'STS', '¥3.56');
insert into car (id, make, model, price) values (878, 'Volvo', '940', '¥2.44');
insert into car (id, make, model, price) values (879, 'Dodge', 'Ram 2500 Club', '¥4.39');
insert into car (id, make, model, price) values (880, 'Kia', 'Optima', '¥9.29');
insert into car (id, make, model, price) values (881, 'Chevrolet', 'Express', '¥0.64');
insert into car (id, make, model, price) values (882, 'Volvo', 'S80', '¥8.79');
insert into car (id, make, model, price) values (883, 'Chrysler', 'Town & Country', '¥9.58');
insert into car (id, make, model, price) values (884, 'BMW', 'M Roadster', '¥4.10');
insert into car (id, make, model, price) values (885, 'Mazda', 'Protege', '¥3.51');
insert into car (id, make, model, price) values (886, 'Toyota', 'Celica', '¥2.04');
insert into car (id, make, model, price) values (887, 'Nissan', 'Maxima', '¥1.22');
insert into car (id, make, model, price) values (888, 'Hyundai', 'Azera', '¥2.86');
insert into car (id, make, model, price) values (889, 'Maserati', 'Coupe', '¥7.01');
insert into car (id, make, model, price) values (890, 'BMW', '7 Series', '¥2.95');
insert into car (id, make, model, price) values (891, 'Chevrolet', 'Astro', '¥4.46');
insert into car (id, make, model, price) values (892, 'Buick', 'Somerset', '¥3.93');
insert into car (id, make, model, price) values (893, 'Chrysler', 'Crossfire', '¥3.16');
insert into car (id, make, model, price) values (894, 'Nissan', '200SX', '¥2.55');
insert into car (id, make, model, price) values (895, 'Infiniti', 'FX', '¥7.35');
insert into car (id, make, model, price) values (896, 'Chevrolet', 'Venture', '¥3.12');
insert into car (id, make, model, price) values (897, 'Mercury', 'Sable', '¥9.50');
insert into car (id, make, model, price) values (898, 'Chevrolet', 'Impala', '¥1.49');
insert into car (id, make, model, price) values (899, 'GMC', 'Acadia', '¥9.15');
insert into car (id, make, model, price) values (900, 'GMC', 'Savana 3500', '¥3.20');
insert into car (id, make, model, price) values (901, 'Lamborghini', 'Gallardo', '¥0.69');
insert into car (id, make, model, price) values (902, 'Hyundai', 'Tucson', '¥8.94');
insert into car (id, make, model, price) values (903, 'BMW', '1 Series', '¥1.84');
insert into car (id, make, model, price) values (904, 'Daewoo', 'Lanos', '¥0.61');
insert into car (id, make, model, price) values (905, 'Chevrolet', 'Corvette', '¥8.79');
insert into car (id, make, model, price) values (906, 'Dodge', 'Caravan', '¥3.11');
insert into car (id, make, model, price) values (907, 'Ford', 'Mustang', '¥3.89');
insert into car (id, make, model, price) values (908, 'Mazda', '626', '¥8.72');
insert into car (id, make, model, price) values (909, 'Acura', 'TSX', '¥2.69');
insert into car (id, make, model, price) values (910, 'Acura', 'RDX', '¥0.21');
insert into car (id, make, model, price) values (911, 'Ford', 'E150', '¥7.90');
insert into car (id, make, model, price) values (912, 'Mazda', 'Mazdaspeed 3', '¥5.89');
insert into car (id, make, model, price) values (913, 'Plymouth', 'Laser', '¥5.98');
insert into car (id, make, model, price) values (914, 'Hyundai', 'Elantra', '¥2.76');
insert into car (id, make, model, price) values (915, 'Pontiac', 'Sunfire', '¥3.84');
insert into car (id, make, model, price) values (916, 'Lexus', 'LS', '¥6.19');
insert into car (id, make, model, price) values (917, 'Volkswagen', 'Jetta III', '¥7.05');
insert into car (id, make, model, price) values (918, 'Mitsubishi', 'Galant', '¥5.91');
insert into car (id, make, model, price) values (919, 'Pontiac', 'Torrent', '¥2.16');
insert into car (id, make, model, price) values (920, 'Volvo', 'XC70', '¥3.31');
insert into car (id, make, model, price) values (921, 'Nissan', '350Z', '¥9.25');
insert into car (id, make, model, price) values (922, 'Ford', 'Excursion', '¥5.93');
insert into car (id, make, model, price) values (923, 'Ford', 'Focus', '¥4.63');
insert into car (id, make, model, price) values (924, 'Corbin', 'Sparrow', '¥8.57');
insert into car (id, make, model, price) values (925, 'Subaru', 'Impreza', '¥1.35');
insert into car (id, make, model, price) values (926, 'Hyundai', 'Santa Fe', '¥1.87');
insert into car (id, make, model, price) values (927, 'Dodge', 'Caliber', '¥1.24');
insert into car (id, make, model, price) values (928, 'Subaru', 'Legacy', '¥0.25');
insert into car (id, make, model, price) values (929, 'Ford', 'F150', '¥6.11');
insert into car (id, make, model, price) values (930, 'BMW', '5 Series', '¥3.72');
insert into car (id, make, model, price) values (931, 'Lexus', 'SC', '¥2.58');
insert into car (id, make, model, price) values (932, 'Ford', 'ZX2', '¥2.26');
insert into car (id, make, model, price) values (933, 'Mercedes-Benz', 'SL-Class', '¥2.16');
insert into car (id, make, model, price) values (934, 'Subaru', 'Leone', '¥3.53');
insert into car (id, make, model, price) values (935, 'Land Rover', 'Discovery Series II', '¥4.49');
insert into car (id, make, model, price) values (936, 'Oldsmobile', 'Bravada', '¥3.60');
insert into car (id, make, model, price) values (937, 'Maybach', 'Landaulet', '¥5.49');
insert into car (id, make, model, price) values (938, 'Volkswagen', 'Jetta', '¥8.32');
insert into car (id, make, model, price) values (939, 'Nissan', 'Maxima', '¥2.95');
insert into car (id, make, model, price) values (940, 'Maserati', 'Gran Sport', '¥5.11');
insert into car (id, make, model, price) values (941, 'Suzuki', 'Aerio', '¥4.91');
insert into car (id, make, model, price) values (942, 'GMC', 'Canyon', '¥4.33');
insert into car (id, make, model, price) values (943, 'Chevrolet', 'Camaro', '¥4.57');
insert into car (id, make, model, price) values (944, 'Chevrolet', 'Silverado 2500', '¥2.84');
insert into car (id, make, model, price) values (945, 'Dodge', 'Dakota', '¥0.73');
insert into car (id, make, model, price) values (946, 'Land Rover', 'Range Rover Sport', '¥5.93');
insert into car (id, make, model, price) values (947, 'Dodge', 'Neon', '¥1.30');
insert into car (id, make, model, price) values (948, 'Infiniti', 'Q', '¥8.09');
insert into car (id, make, model, price) values (949, 'Ford', 'E250', '¥1.31');
insert into car (id, make, model, price) values (950, 'Tesla', 'Model S', '¥9.55');
insert into car (id, make, model, price) values (951, 'Pontiac', 'Grand Prix', '¥7.76');
insert into car (id, make, model, price) values (952, 'Saab', '9-5', '¥3.73');
insert into car (id, make, model, price) values (953, 'Ford', 'Explorer Sport Trac', '¥0.55');
insert into car (id, make, model, price) values (954, 'Cadillac', 'CTS', '¥9.74');
insert into car (id, make, model, price) values (955, 'Dodge', 'Ram 2500', '¥0.18');
insert into car (id, make, model, price) values (956, 'Toyota', 'TundraMax', '¥9.10');
insert into car (id, make, model, price) values (957, 'Aston Martin', 'V8 Vantage', '¥2.91');
insert into car (id, make, model, price) values (958, 'Chevrolet', 'Camaro', '¥7.47');
insert into car (id, make, model, price) values (959, 'MG', 'MGB', '¥3.05');
insert into car (id, make, model, price) values (960, 'Chevrolet', 'Sportvan G30', '¥4.72');
insert into car (id, make, model, price) values (961, 'Chrysler', 'Town & Country', '¥2.20');
insert into car (id, make, model, price) values (962, 'Mazda', 'B-Series Plus', '¥6.60');
insert into car (id, make, model, price) values (963, 'Toyota', 'Camry', '¥1.74');
insert into car (id, make, model, price) values (964, 'Ford', 'Five Hundred', '¥8.86');
insert into car (id, make, model, price) values (965, 'Cadillac', 'Seville', '¥3.15');
insert into car (id, make, model, price) values (966, 'BMW', 'X5', '¥8.48');
insert into car (id, make, model, price) values (967, 'Mitsubishi', 'Lancer Evolution', '¥3.22');
insert into car (id, make, model, price) values (968, 'Chevrolet', 'Silverado 1500', '¥6.57');
insert into car (id, make, model, price) values (969, 'Buick', 'Hearse', '¥6.24');
insert into car (id, make, model, price) values (970, 'Pontiac', 'Grand Prix', '¥2.18');
insert into car (id, make, model, price) values (971, 'Austin', 'Mini', '¥5.37');
insert into car (id, make, model, price) values (972, 'Ford', 'Fusion', '¥0.31');
insert into car (id, make, model, price) values (973, 'Bentley', 'Continental', '¥3.15');
insert into car (id, make, model, price) values (974, 'Jaguar', 'XF', '¥2.63');
insert into car (id, make, model, price) values (975, 'Chrysler', '300', '¥0.05');
insert into car (id, make, model, price) values (976, 'Porsche', '911', '¥2.35');
insert into car (id, make, model, price) values (977, 'Volvo', 'C70', '¥2.84');
insert into car (id, make, model, price) values (978, 'Infiniti', 'Q', '¥1.05');
insert into car (id, make, model, price) values (979, 'Saab', '9-5', '¥1.05');
insert into car (id, make, model, price) values (980, 'BMW', '760', '¥8.00');
insert into car (id, make, model, price) values (981, 'Jaguar', 'XJ', '¥4.40');
insert into car (id, make, model, price) values (982, 'Mitsubishi', 'Mighty Max', '¥5.83');
insert into car (id, make, model, price) values (983, 'Pontiac', 'Grand Prix', '¥2.46');
insert into car (id, make, model, price) values (984, 'Dodge', 'Stratus', '¥7.72');
insert into car (id, make, model, price) values (985, 'Nissan', 'Titan', '¥0.78');
insert into car (id, make, model, price) values (986, 'Mazda', 'B-Series Plus', '¥5.88');
insert into car (id, make, model, price) values (987, 'Lincoln', 'Town Car', '¥0.92');
insert into car (id, make, model, price) values (988, 'Dodge', 'Caravan', '¥9.43');
insert into car (id, make, model, price) values (989, 'Kia', 'Sorento', '¥1.62');
insert into car (id, make, model, price) values (990, 'Chevrolet', 'Cruze', '¥2.26');
insert into car (id, make, model, price) values (991, 'Cadillac', 'Escalade ESV', '¥3.46');
insert into car (id, make, model, price) values (992, 'Plymouth', 'Prowler', '¥2.87');
insert into car (id, make, model, price) values (993, 'Toyota', 'MR2', '¥2.28');
insert into car (id, make, model, price) values (994, 'Jeep', 'Wrangler', '¥5.86');
insert into car (id, make, model, price) values (995, 'Honda', 'Element', '¥5.66');
insert into car (id, make, model, price) values (996, 'Saab', '9-5', '¥4.01');
insert into car (id, make, model, price) values (997, 'Ferrari', '612 Scaglietti', '¥6.39');
insert into car (id, make, model, price) values (998, 'Dodge', 'Nitro', '¥6.48');
insert into car (id, make, model, price) values (999, 'Porsche', '911', '¥8.27');
insert into car (id, make, model, price) values (1000, 'Mitsubishi', 'Montero', '¥0.36');
